Repository nlpsandbox/nlpsandbox.io, pull requests merged in 2021-02, with the labels that each got.

#10 Add initial SOP for returning logs
  images/elk/kibana-discover-menu.png
  images/elk/kibana-discover-open.png
  images/elk/kibana-discover-search-by-sub-id.png
  images/elk/kibana-discover-timeframe.png
  wiki/608145-Submissionlogs.md
  wiki/wiki_config.json
Labels: Priority: Low

#33 Add markdown linter, its config and add it to CI/CD
  .github/workflows/ci.yml
  .gitignore
  .markdownlint.json
  package-lock.json
  package.json
  wiki/.markdownlintignore
  wiki/604836-DevelopersTeams.md
  wiki/607367-Admin.md
  wiki/608145-SubmissionLogs.md
Labels: Priority: Medium

#34 Update README, add CONTRIBUTING and CODE_OF_CONDUCT
  .markdownlint.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package.json
Labels: Priority: Low

#39 Dataset
  .markdownlint.json
  wiki/608223-2014i2b2NLPDeidChallengeDataset.md
Labels: Priority: High

#48 Add Synapse Tutorial
  images/elk/kibana-discover-menu.png
  images/elk/kibana-discover-open.png
  images/elk/kibana-discover-search-by-sub-id.png
  images/elk/kibana-discover-timeframe.png
  images/synapse-project-docker-repository.png
  wiki/604836-UsersTeams.md
  wiki/608450-SynapseEnvironment.md
  wiki/wiki_config.json
Labels: Priority: Medium

#43 Start documenting physical addresss TP, TN, etc.
  wiki/608041-PhysicalAddressAnnotationLeaderboard.md
Labels: Priority: High

#47 Update address type leaderboard
  wiki/608041-PhysicalAddressAnnotationLeaderboard.md
Labels: Priority: Medium

#52 Update tasks and evaluation
  .gitignore
  wiki/.markdownlintignore
  wiki/604837-ParticipationOverview.md
  wiki/607935-Tasks.md
  wiki/608036-PersonNameAnnotation.md
  wiki/608037-DateAnnotation.md
  wiki/608037-PHIAnnotationDeIdentification.md
  wiki/wiki_config.json
Labels: Priority: Medium

#60 Document how to login to Synapse Docker registry using PAT
  wiki/608484-BenchmarkaTool.md
Labels: Priority: Medium

#61 Add lock config
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue_report.md
  .github/workflows/ci.yml
  .github/workflows/lock.yml
Labels: Priority: Low
